analyzer:
  errors:
    missing_required_param: error
    prefer_const_declarations: warning
    prefer_const_constructors: warning
    exhaustive_cases: error
    argument_type_not_assignable: error
    avoid_escaping_inner_quotes: info

linter:
  rules:
    prefer_relative_imports: true
    prefer_const_declarations: true
    prefer_const_constructors: true
    exhaustive_cases: true
    always_specify_types: false
    avoid_print: true
    sort_pub_dependencies: false
    directives_ordering: true
    avoid_bool_literals_in_conditional_expressions: false
    use_build_context_synchronously: true
    avoid_escaping_inner_quotes: false
    avoid_dynamic_calls: false
    depend_on_referenced_packages: false
