name: tikeetron_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # blockchain
  tron: ^0.0.2
  web3dart: ^2.7.3
  bdk_flutter: ^0.30.0
  bip32: ^2.0.0
  bip39: ^1.0.6
  bip32_bip44: ^1.0.0
  on_chain: ^4.2.0

  # UI
  badges: ^3.1.2
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  auto_size_text: ^3.0.0
  mobile_scanner: 5.2.3
  figma_squircle:
    git:
      url: https://github.com/mark8044/figma_squircle
      ref: fix0
  flutter_carousel_widget: ^2.3.0
  show_up_animation: ^2.0.0
  flutter_cache_manager: ^3.4.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  qr_flutter_new: ^1.0.2
  google_fonts: ^6.2.1
  modal_bottom_sheet: ^3.0.0
  pin_code_fields: ^8.0.1
  pull_to_refresh: ^2.0.0
  slide_to_act: ^2.0.2
  qr_flutter: ^4.1.0
  syncfusion_flutter_charts:
    git:
      url: https://github.com/Luvti/flutter-widgets
      path: packages/syncfusion_flutter_charts
      ref: 15e3c4a95e3cf2e2393755bf5aa11c0206ed6dea
  flutter_markdown: ^0.7.3
  typewritertext: ^3.0.9

  # State Management
  flutter_bloc: ^8.1.6

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.4

  # Storage
  hive: ^2.2.3
  path_provider: ^2.1.4
  flutter_secure_storage: ^9.2.2

  # Navigation
  auto_route: ^9.2.0

  # Others
  equatable: ^2.0.5
  form_validator: ^2.1.1
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  timeago: ^3.7.0
  cupertino_calendar_picker: ^2.0.0+1
  carousel_slider: ^5.0.0
  encrypt: ^5.0.1
  vibration: ^2.0.0
  collection: ^1.18.0
  local_auth: ^2.3.0
  package_info_plus: ^8.0.2
  blockies: ^0.1.2
  url_launcher: ^6.3.0

  # Network
  dio: ^5.7.0
  dio_cache_interceptor: ^3.4.2
  connectivity_plus: ^6.0.3

  # ENV
  secure_dotenv: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  injectable_generator: ^2.6.2
  secure_dotenv_generator: ^1.0.1

  # Tools
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/illustrations/
    - assets/images/
    - assets/svg/
    - assets/images/token/
    - assets/images/logo/
